services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: argumentor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    environment:
      # DEV: "true"
      # USE_LLM_EVALUATOR: "false"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:password@db:5432/argumentor"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:8000 src.app:app"

volumes:
  pgdata:
