"""Add completed_achievements column to Answer model

Revision ID: 0208681c3092
Revises: 96a3fc5e3bd3
Create Date: 2025-03-11 14:22:24.188243

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0208681c3092"
down_revision = "96a3fc5e3bd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "completed_achievements", sa.JSON(), nullable=True, server_default="[]"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answer", schema=None) as batch_op:
        batch_op.drop_column("completed_achievements")

    # ### end Alembic commands ###
