"""Add email field to Feedback model

Revision ID: 0b6bc351f3fe
Revises: 65909b69ff2f
Create Date: 2025-03-06 14:01:34.629138

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b6bc351f3fe"
down_revision = "65909b69ff2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_column("email")

    # ### end Alembic commands ###
