"""Add monthly limits tracking

Revision ID: 65909b69ff2f
Revises: fix_timezone_handling
Create Date: 2025-03-05 22:47:08.832750

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65909b69ff2f"
down_revision = "fix_timezone_handling"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("monthly_eval_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("monthly_voice_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_monthly_eval_reset", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_monthly_voice_reset", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_monthly_voice_reset")
        batch_op.drop_column("last_monthly_eval_reset")
        batch_op.drop_column("monthly_voice_count")
        batch_op.drop_column("monthly_eval_count")

    # ### end Alembic commands ###
