"""Add preferred language

Revision ID: 6ef2eea7ee62
Revises: fb1265041b0e
Create Date: 2025-02-18 11:43:59.948459

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ef2eea7ee62"
down_revision = "fb1265041b0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("preferred_language", sa.String(length=2), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("preferred_language")

    # ### end Alembic commands ###
