"""Add completed_achievement column to Answer model

Revision ID: 96a3fc5e3bd3
Revises: 2b5aed863200
Create Date: 2025-03-11 14:16:08.671757

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "96a3fc5e3bd3"
down_revision = "2b5aed863200"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("completed_achievement", sa.String(length=50), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answer", schema=None) as batch_op:
        batch_op.drop_column("completed_achievement")

    # ### end Alembic commands ###
