"""Add stripe details to manage subscriptions

Revision ID: f4a6b92d6b59
Revises: 0b6bc351f3fe
Create Date: 2025-03-06 19:47:30.106579

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f4a6b92d6b59"
down_revision = "0b6bc351f3fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("stripe_customer_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("subscription_end_date", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("is_subscription_canceled", sa.Boolean(), nullable=True)
        )
        batch_op.create_unique_constraint(None, ["stripe_subscription_id"])
        batch_op.create_unique_constraint(None, ["stripe_customer_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("is_subscription_canceled")
        batch_op.drop_column("subscription_end_date")
        batch_op.drop_column("stripe_subscription_id")
        batch_op.drop_column("stripe_customer_id")

    # ### end Alembic commands ###
