"""Add input mode

Revision ID: fb85b50c3b2c
Revises: 6ef2eea7ee62
Create Date: 2025-02-19 14:46:52.415539

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fb85b50c3b2c"
down_revision = "6ef2eea7ee62"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("input_mode", sa.String(length=10), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answer", schema=None) as batch_op:
        batch_op.drop_column("input_mode")

    # ### end Alembic commands ###
